[plugin]
repository = "https://github.com/Pythyu/WhereIsMyMouse.git"
commit = "cdae978de5943c6edf3ae4be764c1cb6a59444cb"
owners = [
    "Pythyu",
]
project_path = "WhereIsMyMouse"
changelog = """ Changes :
    - Upgraded to API 9 by @sersorrel
    - Added option to enable only in combat
    - Added Icon
"""
