[plugin]
repository = "https://github.com/Pythyu/WhereIsMyMouse.git"
commit = "1dea369033d52db27ad82505518edb37cd0580c0"
owners = [
    "Pythyu",
]
project_path = "WhereIsMyMouse"
changelog = """ Changes :
    - Upgraded to 6.4 by @sersorrel
    - Added option to enable only in combat
"""
