[plugin]
repository = "https://github.com/Pythyu/WhereIsMyMouse.git"
commit = "e3959e1f45a22405cbe5f98a47cf1d5cad55a7bf"
owners = [
    "Pythyu",
]
project_path = "WhereIsMyMouse"
changelog = """ Changes :
    - Upgraded to API 9 by @sersorrel
    - Added option to enable only in combat
    - Added Icon
"""
