[plugin]
repository = "https://github.com/Pythyu/WhereIsMyMouse.git"
commit = "c4d5347f63304e53ae02f9b889bcbee4d389028f"
owners = [
    "Pythyu",
]
project_path = "WhereIsMyMouse"
changelog = """Changes :
  - adding NoFocusOnAppearing to plugin window by @ShioIna
  - net8 & update for api 10 by @avail
"""
